### ISSUE TITLE
Error is displayed on keeping the device idle for the time specified in "Recheck the access requirements after (minutes of inactivity)" parameter

### ISSUE THREAD

**Issue by raaz252** [microsoftconnect/intune-app-wrapping-tool-ios#122] opened 2024-07-31 13:01 UTC
**Describe the bug:**
Issue with wrapped iOS build. After leaving the app and keeping the device idle at Home Screen for 2 minutes(minutes of inactivity), MSALErrorDomain Code=-50000 is displayed .

**To Reproduce**
1. Wrap the IPA file with the intune-app-wrapping-tool (any b/w v19.1 to v19.5.0)
2. Install the app on user device and launch the app
3. Log in with the credentials 
4. After user gets successfully logged in , leave the app and go to Home Screen of device and keep the device idle for 2 minutes(minutes of inactivity)
5. Again launch the app , MSALErrorDomain Code=-50000 will be displayed

**Expected behavior:**
The app should move forward to the next screen without any error

**Screenshots and logs:**
![Image2](https://github.com/user-attachments/assets/e40684c8-01e5-4e30-912f-1915a39da2bf)
[IntuneMAMDiagnosticFiles.txt](https://github.com/user-attachments/files/16442043/IntuneMAMDiagnosticFiles.txt)
**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: IOS 17.5.1

**Intune app wrapping tool (please complete the following information):**
- What version of the wrapper are you using? Are you using the latest version?
   Issue appears with all releases between 19.1 to 19.5
- What platform is your app based in (Java, Xamarin based, Cordova, etc)?
   Xcode 15.4 and iOS sdk v17.4
- For pre-wrapping errors, does the app build without being wrapped?
   Without wrapping, it is working fine.
- For post-wrapping errors, does the app launch without being wrapped?
   Yes, it is getting launched . 
- Do you see a trend with it only being reproduced on a specific device?
   No

**Additional context:**
- ***Recheck the access requirements after (minutes of inactivity)*** is set to be 2 minutes at Intune Portal .
- Microsoft Authenticator should also be installed as it will be needed while log in .

**Comment by wangxiaoms** [comment] 2024-08-02 03:39
Hi, is this happening to specific user/device or all user/devices? Can you try re-installation of latest Authenticator?

**Comment by raaz252** [comment] 2024-08-06 05:47
Hi ,
1. Is this happening to specific user/device or all user/devices?
Yes it is happening on all iOS devices.
2.Can you try re-installation of latest Authenticator?
It is still happening after reinstallation of Authenticator.

**Comment by wangxiaoms** [comment] 2024-08-08 02:42
Could you provide the wrapping command parameter values, pre-wrapping app file, the wrapped ipa, the info.plist? Also if possible videos of what's happening at first login and when user launch app the second time after inactivity timer. My email wangxiao@microsoft.com.

**Comment by wangxiaoms** [comment] 2024-08-18 23:24
> Could you provide the wrapping command parameter values, pre-wrapping app file, the wrapped ipa, the info.plist? Also if possible videos of what's happening at first login and when user launch app the second time after inactivity timer. My email [wangxiao@microsoft.com](mailto:wangxiao@microsoft.com).

@raaz252 are you able to provide the required evidences, or I would close the issue if no activity.

**Comment by wangxiaoms** [comment] 2024-08-26 23:45
Closing because of inactivity

**Comment by shree1497** [comment] 2024-09-04 15:58
Hey @wangxiaoms I am observing this same issue on iOS 18 Beta.
This issue was pretty inconsistent on iOS 17 at 1/10 times, but on iOS 18, I am able to reproduce this issue 6/10 times.

I have also shared all the details you asked on your email. 
Subject: Intune iOS Wrapping Tool Issue #122: Inactivity Timeout Error

Kindly let me know if there is anything else you need from my side.

**Comment by wangxiaoms** [comment] 2024-09-05 07:53
Hi @shree1497 please wait for further notice on iOS 18 and Xcode 16 support.

**Comment by wangxiaoms** [comment] 2024-09-16 00:01
@shree1497 can you try the latest SDK 19.7.0 (stilll Xcode 15).
https://github.com/microsoftconnect/intune-app-wrapping-tool-ios/releases/tag/19.7.0

**Comment by shree1497** [comment] 2024-09-16 07:32
Hi @wangxiaoms , as you suggested, I tried by wrapping my app with Intune iOS Wrapping Tool Version 19.7.0.
I was still able to reproduce this issue. 

Let me know if there is anything I can provide to help you investigate this further.

**Comment by wangxiaoms** [comment] 2024-09-16 07:57
@shree1497 can you send me the wrapping command parameter values, pre-wrapping app file, the wrapped ipa, the info.plist, a screen recording video, understood you sent some before but can you use the latest SDK and send those info to me again.

**Comment by shree1497** [comment] 2024-09-16 09:28
@wangxiaoms, I have sent the details you requested.

**Comment by wangxiaoms** [comment] 2024-11-21 22:54
Closing as fix provided, you can still update here if needed.

**Closed by wangxiaoms** 2024-11-21 22:54 UTC
